### ISSUE TITLE
Command /bin/sh failed with exit code 127

### ISSUE THREAD

**Issue by av0c0der** [lvillani/carthage-copy-frameworks#1]
I'm trying to avoid error prone of manually entering frameworks names & want to use this solution with Xcode 8 Beta, but faced this problem

**Comment by lvillani** [comment]
Can you report the exact error printed on the console?

**Comment by av0c0der** [comment]
Xcode report:

`frameworksTest.build/Debug-iphoneos/frameworksTest.build/Script-9DD6A0231D3E042F00445CE8.sh: line 2: carthage-copy-fram: command not found
Command /bin/sh failed with exit code 127`

And script is installed:

`Requirement already satisfied (use --upgrade to upgrade): carthage-copy-frameworks in /private/var/jauzee/Library/Python/2.7/lib/python/site-packages`

**Comment by lvillani** [comment]
It says `carthage-copy-fram`, it looks like there's a typo somewhere...

**Comment by av0c0der** [comment]
Maybe typo in script? Are you used it ever?

<img width="681" alt="screen shot 2016-07-19 at 12 52 07" src="https://cloud.githubusercontent.com/assets/7991920/16945905/c0ce5c16-4daf-11e6-9289-e5fd124de996.png">

**Comment by lvillani** [comment]
Can you send me the Xcode-generated shell script that's failing? (Its path is printed in the error, e.g. `frameworksTest.build/Debug-iphoneos/frameworksTest.build/Script-9DD6A0231D3E042F00445CE8.sh`)

**Comment by av0c0der** [comment]
``` ruby
#!/bin/sh
carthage-copy-frameworks
```

This is the script from that path

**Comment by lvillani** [comment]
That's weird. Did you try running the script manually (with the required environment variables) making sure it works there first?

Please note that Xcode 8 is a beta, thus isn't supported.

**Comment by lvillani** [comment]
I'm closing this one, feel free to re-open it if it happens again.
