### ISSUE TITLE
Custom path to carthage directory

### ISSUE THREAD

**Issue by tbaranes** [lvillani/carthage-copy-frameworks#3]
In my project, the xcodeproj is not at the same level as the carthage directory. We have the carthage directory at the root with the workspace, but the xcodeproj is in a subdirectory.

In that state, the script is failing because it can't find the carthage directory. Is there a way to specify a path?

**Comment by lvillani** [comment]
There's no way to specify a path at the moment since that's a use-case I never encountered, but I welcome any contribution for adding such feature.

**Comment by JeanAzzopardi** [comment]
I've created a P.R. for this purpose, wonder if you can give it a look @lvillani 

Thanks!

**Comment by lvillani** [comment]
This feature should now be present in 1.1.0 released yesterday.
