### ISSUE TITLE
Standalone script

### ISSUE THREAD

**Issue by leoneparise** [lvillani/carthage-copy-frameworks#4]
Hey! I'm using your script in my apps and it's awesome! Now my app build is much faster thanks to your script.

The only thing I wanna know is, is there a way to provide releases with a standalone script? `pip install carthage-copy-frameworks` only works with you're in a homebrew environment. If you're not using homebrew python version, XCode can't find the command.

I'm thinking to include the script in my project's root folder and execute from there so my team won't need to do anything to configure the project.

Thank you for your amazing script! Again! =)

**Comment by lvillani** [comment]
It's already a stand-alone script that you can install through pip regardless of whether you are using homebrew Python or not. It just needs to the be in the `$PATH`. Using homebrew-python is the fastest way to install it but you are not required to use it.
